### ISSUE TITLE
Package 0.9.0.3 Crashes Codesys

### ISSUE THREAD

**Issue by Hubieg** [Aliazzzz/Monarco-HAT-library-for-CODESYS-V3#4]
This is on Codesys V3.5 SP11 Patch 3 64 bit, possibly important it is running in a VMWare virtual machine Windows 7 64 bit. This had no effect however in installing the Pi and Wago packages.

Loading the package file results in an immediate crash notification. Selected save crash report but Codesys is locked up in the package installer screen. Only way out is to kill entire Codesys process. Cannot find any traces of the crash report....BUMMER!

**Comment by Aliazzzz** [comment]
The package has been tested via 

* i7 with VirtualBox, 16GB RAM,  (i use Virtualbox as it is free),
* WIN10 PRO x64,
* Codesys V3.5 SP11 Patch 3 - 32 bit IDE
* Codesys V3.5 SP11 Patch 3 - 64 bit IDE installed on same machine (side by side, no issues)
* I installed WAGO, RPi, Beaglebone packages etc, etc.
* 2nd **clean** virtual machine to deploy the software for testing purpose both x32 and x64 IDE's
* The package has been also tested on WIN7 x32 and a WIN7 x64 machine
So, I "think" the issue may be your vmware machine itself.

**workaround**  you can rename the package file to .zip and unzip it somewhere and installe these files loose via and IDE of your choice.

Hope this helps!

**Comment by Hubieg** [comment]
My fault! Corrupted in transfer. SORRY!!
